# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded AECFunctions 1.0 [list source [file join $dir AECFunctions.tcl]]
package ifneeded AnimatedHeader 1.0 [list source [file join $dir AnimatedHeader.tcl]]
package ifneeded BWFileEntry 1.0.0 [list source [file join $dir fileentry.tcl]]
package ifneeded BWHelp 1.0.0 [list source [file join $dir BWHelp.tcl]]
package ifneeded BWLabelComboBox 1.0.0 [list source [file join $dir labelcombobox.tcl]]
package ifneeded BWLabelSpinBox 1.0.0 [list source [file join $dir labelspinbox.tcl]]
package ifneeded BWStdMenuBar 1.0 [list source [file join $dir BWStdMenuBar.tcl]]
package ifneeded DWpanedw 1.0 [list source [file join $dir panedw.tcl]]
package ifneeded DatabaseFunctions 1.0 [list source [file join $dir DatabaseFunctions.tcl]]
package ifneeded EditWindow 1.0 [list source [file join $dir EditWindow.tcl]]
package ifneeded ImportV1Ascii 1.0 [list source [file join $dir ImportV1Ascii.tcl]]
package ifneeded ImportV2Ascii 1.0 [list source [file join $dir ImportV2Ascii.tcl]]
package ifneeded LabelSelectColor 1.0 [list source [file join $dir labelselectcolor.tcl]]
package ifneeded MainWindow 1.0 [list source [file join $dir mainwindow.tcl]]
package ifneeded PrintFunctions 1.0 [list source [file join $dir PrintFunctions.tcl]]
package ifneeded SearchWindow 1.0 [list source [file join $dir SearchWindow.tcl]]
package ifneeded Splash 1.0 [list source [file join $dir splash.tcl]]
